### ISSUE TITLE
Cannot start server

### ISSUE THREAD

**Issue by amidisturbing** [alexa-js/alexa-app-server#104]
When typing 
`sudo node server`
in the alexa-app-server/examples directory
I get the following error:
```module.js:327
    throw err;
    ^

Error: Cannot find module 'hotswap'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/alexa-app-server/index.js:1:77)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```
I am working on a RaspberryPi 3 with Raspbian OS (Jessie)

**Comment by cOGeorgcO** [comment]
I'm facing the same problem.
What was your solution ?

**Comment by amidisturbing** [comment]
@cOGeorgcO Your UPDATE shows a solid solution. 👍 
 `npm install` (or with option `-g` for global mode) installs all the needed dependencies.  If really just the module `hotswap` would be missing  `npm install hotswap` would also do the trick and might save you some time.
