### ISSUE TITLE
Testing interface

### ISSUE THREAD

**Issue by TomMettam** [alexa-js/alexa-app-server#19]
Amazon certification rules dictate that the end point must verify that the request has come from Alexa. However, when verification is ON, this breaks the local testing tool. 

The testing tool probably needs to be automatically disabled when config.verify is on. In fact, the testing tool should probably be disabled in **any** production environment.

**Comment by jradwan** [comment]
I just ran into this myself.

**Comment by jradwan** [comment]
Here's the error that's thrown when trying to use the built-in tester with verification enabled:

```
[2017-01-04T13:06:18.536Z] ReferenceError: er is not defined
    at Object.handle (/usr/local/alexa-app-server/index.js:97:57)
    at next_layer (/usr/local/alexa-app-server/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/usr/local/alexa-app-server/node_modules/express/lib/router/route.js:107:5)
    at c (/usr/local/alexa-app-server/node_modules/express/lib/router/index.js:195:24)
    at Function.proto.process_params (/usr/local/alexa-app-server/node_modules/express/lib/router/index.js:251:12)
    at next (/usr/local/alexa-app-server/node_modules/express/lib/router/index.js:189:19)
    at Layer.handle (/usr/local/alexa-app-server/index.js:79:15)
    at trim_prefix (/usr/local/alexa-app-server/node_modules/express/lib/router/index.js:226:17)
    at c (/usr/local/alexa-app-server/node_modules/express/lib/router/index.js:198:9)
    at Function.proto.process_params (/usr/local/alexa-app-server/node_modules/express/lib/router/index.js:251:12)
    at next (/usr/local/alexa-app-server/node_modules/express/lib/router/index.js:189:19)
    at next (/usr/local/alexa-app-server/node_modules/express/lib/router/index.js:166:38)
    at next (/usr/local/alexa-app-server/node_modules/express/lib/router/index.js:166:38)
    at next (/usr/local/alexa-app-server/node_modules/express/lib/router/index.js:166:38)
    at next (/usr/local/alexa-app-server/node_modules/express/lib/router/index.js:166:38)
    at Layer.staticMiddleware [as handle] (/usr/local/alexa-app-server/node_modules/express/node_modules/serve-static/index.js:55:61)
    at trim_prefix (/usr/local/alexa-app-server/node_modules/express/lib/router/index.js:226:17)
    at c (/usr/local/alexa-app-server/node_modules/express/lib/router/index.js:198:9)
    at Function.proto.process_params (/usr/local/alexa-app-server/node_modules/express/lib/router/index.js:251:12)
    at next (/usr/local/alexa-app-server/node_modules/express/lib/router/index.js:189:19)
    at IncomingMessage.<anonymous> (/usr/local/alexa-app-server/index.js:184:5)
    at IncomingMessage.emit (events.js:92:17)
```

**Comment by TomMettam** [comment]
jradwan: That's actually a different issue (a typo) - i've already fixed it in my pull request.

**Comment by jradwan** [comment]
@TomMettam Ok, thanks!

**Comment by dblock** [comment]
The typo was fixed via https://github.com/alexa-js/alexa-app-server/commit/25789e16111946bfc8553bdb6c00a1cffba97764, FYI. The rest is a valid feature request.

**Comment by tejashah88** [comment]
PR #36 should address this.

**Comment by dblock** [comment]
Closing (feel free to close @tejashah88 things that look fixed).
